[colors]
# Color or grayscale.
color_mode = "color"

[paths]
input_dir = "~/Leon (Kopia)"
output_dir = "processed_images"

[processes.adjust_brightness_and_contrast]
enabled = false
# alpha: Contrast value. Value between 0 and 1 lowers the contrast, while value
# above 1 increases it.
# Default = 1.0
alpha = "None"
# beta: Brightness value. Suggested value between -127 and 127.
# Default = 0
beta = "None"

[processes.bilateral_filter]
enabled = false
# d: Diameter of the pixel neighborhood used for filtering; if d == 0 diameter
#is calculated based only on sigma_space.
# Default = 9
d = "None"
# sigmaColor: Color deviation value. Higher value means higher tonal spread,
#i.e. colors farther away from each other will be mixed.
# Default = 75
sigmaColor = "None"
# sigmaSpace: Second parameter defining extent of pixel neighborhood; higher
# value means that the further pixels will be mixed if their colors lie within
# sigmaColor range.
# Default = 75
sigmaSpace = "None"

[processes.clahe]
enabled = false
# clipLimit: Threshold for contrast limiting.
# Default = 40
clipLimit = "None"
# tileGridSize: Sets row and column size of tile used to divide image for
# applying clahe.
# Default = (8, 8)
tileGridSize = "None"

[processes.denoise_filter]
enabled = false
# searchWindowSize: Size in pixels of the window used to compute weighted
# average for given pixel; should be odd number.
# Default = 21
searchWindowSize = "None"
# templateWindowSize: Size in pixels of the template patch used to compute
# weights; should be odd number.
# Default = 7
templateWindowSize = "None"
# h and hColor: Filter strength for grayscale (h) and color (hColor)
# images. Higher value means better noise removal at the cost of removing image
# details and distorting colors (in color images).
# Default hColor = 10 and h = 30
hColor = "None"
h = "None"

[processes.reverse_colors]
enabled = false

[processes.rotate_image]
enabled = false
# Correct angle values are: 90, 180, 270.
angle = 90

[processes.sharpen_image]
enabled = false
# Choose between sharpen and unsharp_mask.
kernel = "unsharp_mask"
# filter_strength: As name implies; it is basically weigth for performing
# alpha blending of original and processed images; correct values: between
# 0 and 1.
# Default = 0.5
filter_strength = "None"

[processes.stress]
enabled = true
# Convert color mode to grayscale.
convert_to_grayscale = false
# Sampling radius, i.e. max distance from pixel from which samples are being
# drawn; correct values: positive integers.
radius = "None"
# Number of samples taken for each pixel; correct values: positive integers.
sampling = 3
# Number of iterations, i.e. how many times STRESS will be applied before
# writing output image; correct values: positive integers.
iterations = 10
# Gamma correction; correct values: floating point from 1.0 (no corrections).
gamma = 1.25

[processes.thresholding]
enabled = false
# adaptiveMethod: Choose between thresholding methods: mean [0] or gaussian
# [1].
# Default = 0
adaptiveMethod = "None"
# block_size: Size of pixel neighborhood used to calculate threshold value.
# Should be odd number.
# Default = 199
blockSize = "None"
# C: Constant value subtracted from the mean or weighted (gaussian
# thresholding) sum of neighboring pixels.
# Default = 40
C = "None"
# maxValue: Max value that can be assigned to pixel.
# Default = 255
maxValue = "None"
# Thresholding type.
# Default = cv2.THRESH_BINARY
thresholdType = "None"

[write_output.write_image]
enabled = true
# Choose between JPG and PNG.
file_extension = "jpg"
# For JPEG set between 0 and 100; for PNG it is translated to compression
# ratio, set between 1 and 10 (highest compression).
quality = 80

[write_output.write_pdf]
# I'm thinking about removing this at all, without compression it's not very
# useful. Except maybe LZW applied for each image before merging would do?
enabled = false
#images_path = "processed_images"
pdf_name = "Document"
pdf_compression = "None"
